# ai/chatbot_client.py  — STUB BOILERPLATE until provider is announced.
# Implements AIClient so the evaluation pipeline runs end-to-end today.
#
# Scaffolding boundary (design.md): this is the ONLY module that changes when
# the AI provider is confirmed. The real request/response handling replaces the
# body of ``complete`` (see the commented block below); everything else in the
# codebase — service orchestration, parsing/validation, scoring — stays put.
import json

import httpx  # noqa: F401 — used by the (future) real provider call below.

from app.ai.base import AIClient
from app.config import settings


class ChatbotClient(AIClient):
    """
    Boilerplate implementation. When the AI provider is announced, fill in the
    real request/response handling here (confirm JSON output, request format,
    token pricing). NOTHING ELSE in the codebase should need to change.
    """

    def __init__(self, api_key: str, base_url: str, model: str, timeout: float = 15.0):
        self._api_key = api_key
        self._base_url = base_url
        self._model = model
        self._timeout = timeout

    def complete(self, prompt: str) -> str:
        # --- real provider call goes here, e.g.: -------------------------
        # with httpx.Client(timeout=self._timeout) as client:
        #     resp = client.post(
        #         f"{self._base_url}/chat/completions",
        #         headers={"Authorization": f"Bearer {self._api_key}"},
        #         json={"model": self._model, "temperature": 0.0,
        #               "messages": [{"role": "user", "content": prompt}]},
        #     )
        #     resp.raise_for_status()
        #     return resp.json()["choices"][0]["message"]["content"]
        # -----------------------------------------------------------------
        # STUB: return a deterministic, contract-shaped placeholder so the
        # pipeline exercises parsing/validation/scoring before the provider
        # exists. Replace this entire method when the provider is announced.
        return self._stub_response(prompt)

    @staticmethod
    def _stub_response(prompt: str) -> str:
        # Shape matches the AI response contract. One "correct" entry per
        # question line found in the prompt; evidence left null (not found).
        n = max(1, prompt.count("Question:"))
        return json.dumps({
            "answers": [{"order": i + 1, "verdict": "correct", "evidence": None}
                        for i in range(n)],
            "evaluation": "Placeholder summary generated by the stub AI client.",
            "recommendation": "Continue practicing reading comprehension regularly.",
        })


def build_ai_client() -> AIClient:
    """Factory used by the evaluation service. Swap implementation here later."""
    return ChatbotClient(
        api_key=settings.AI_API_KEY,
        base_url=settings.AI_BASE_URL,
        model=settings.AI_MODEL,
    )
