import { useEffect, useState } from "react"
import { useLocation, useNavigate } from "react-router-dom"
import {
  ArrowLeft,
  Plus,
  Trash2,
  ClipboardList,
  Sparkles,
} from "lucide-react"
import { PageHeader } from "@/components/layout"
import { Button, Card, Input, Badge } from "@/components/ui"
import { useClassroom } from "@/session/useClassroom"
import { repository, ApiError } from "@/services"
import { SKILLS } from "@/domain/constants"
import "./AssessmentCreatePage.css"

const newQuestion = () => ({
  question_text: "",
  skill: SKILLS[0].key,
  expected_ideas: "",
})

/** Today in YYYY-MM-DD for the default scheduled_for value. */
function todayISO() {
  const d = new Date()
  const mm = String(d.getMonth() + 1).padStart(2, "0")
  const dd = String(d.getDate()).padStart(2, "0")
  return `${d.getFullYear()}-${mm}-${dd}`
}

/** Pad an incoming draft''s questions to at least 3, cap at 5. */
function normalizeQuestions(qs) {
  const mapped = (qs ?? []).slice(0, 5).map((q) => ({
    question_text: q.question_text ?? "",
    skill: SKILLS.some((s) => s.key === q.skill) ? q.skill : SKILLS[0].key,
    expected_ideas: q.expected_ideas ?? "",
  }))
  while (mapped.length < 3) mapped.push(newQuestion())
  return mapped
}

/**
 * AssessmentCreatePage — build a reading assessment and schedule it for the
 * active classroom via the backend. Scheduling creates one assessment per
 * active learner (a batch) and returns a shared access code; we then send the
 * teacher to that batch''s share screen.
 *
 * Two AI-assisted entry points fill this form:
 *   1. A draft handed in via router state (from the Assessments scanner''s
 *      "Draft with AI"), which prefills every field on arrival.
 *   2. The "Draft from the passage with AI" button here, which sends the
 *      current passage text to the extraction endpoint and fills in questions.
 * The teacher always reviews/edits before saving.
 */
export function AssessmentCreatePage() {
  const navigate = useNavigate()
  const location = useLocation()
  const { activeClassroom } = useClassroom()
  const incoming = location.state?.draft ?? null

  const [title, setTitle] = useState(incoming?.title ?? "")
  const [category, setCategory] = useState(incoming?.category ?? "Fiction")
  const [passage, setPassage] = useState(incoming?.passage_text ?? "")
  const [scheduledFor, setScheduledFor] = useState(todayISO())
  const [questions, setQuestions] = useState(
    incoming?.questions
      ? normalizeQuestions(incoming.questions)
      : [newQuestion(), newQuestion(), newQuestion()],
  )
  const [error, setError] = useState(null)
  const [saving, setSaving] = useState(false)
  const [drafting, setDrafting] = useState(false)
  const [draftNote, setDraftNote] = useState(
    incoming?.questions ? "Draft generated by AI — review and edit below." : null,
  )

  // If a draft arrives after mount (navigation state), clear it from history
  // state so a refresh doesn''t silently re-apply it.
  useEffect(() => {
    if (incoming) {
      window.history.replaceState({}, document.title)
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const setQuestion = (i, patch) =>
    setQuestions((qs) => qs.map((q, idx) => (idx === i ? { ...q, ...patch } : q)))
  const addQuestion = () =>
    setQuestions((qs) => (qs.length < 5 ? [...qs, newQuestion()] : qs))
  const removeQuestion = (i) =>
    setQuestions((qs) => (qs.length > 3 ? qs.filter((_, idx) => idx !== i) : qs))

  const canSave =
    title.trim() &&
    passage.trim() &&
    questions.length >= 3 &&
    questions.length <= 5 &&
    questions.every((q) => q.question_text.trim() && q.expected_ideas.trim())

  const draftFromPassage = async () => {
    setError(null)
    setDraftNote(null)
    if (passage.trim().length < 30) {
      setError("Add a longer passage first, then let AI draft the questions.")
      return
    }
    setDrafting(true)
    try {
      const draft = await repository.extractAssessment(passage)
      if (draft.title && !title.trim()) setTitle(draft.title)
      if (draft.category) setCategory(draft.category)
      if (draft.passage_text) setPassage(draft.passage_text)
      setQuestions(normalizeQuestions(draft.questions))
      setDraftNote("Draft generated by AI — review and edit below.")
    } catch (err) {
      if (err instanceof ApiError) {
        setError(err.message || "Couldn’t draft from that text.")
      } else {
        setError("Couldn’t reach the server. Try again shortly.")
      }
    } finally {
      setDrafting(false)
    }
  }

  const onSave = async () => {
    setError(null)
    if (!activeClassroom?.id) {
      setError("Select or create a classroom first.")
      return
    }
    if (!canSave) {
      setError(
        "Add a title, a passage, and 3–5 questions — each with its text and expected ideas.",
      )
      return
    }
    setSaving(true)
    try {
      const summary = await repository.scheduleAssessment({
        classroom_id: activeClassroom.id,
        title: title.trim(),
        category: category.trim() || "Reading",
        passage_text: passage.trim(),
        scheduled_for: scheduledFor,
        questions: questions.map((q) => ({
          question_text: q.question_text.trim(),
          skill: q.skill,
          expected_ideas: q.expected_ideas.trim(),
        })),
      })
      navigate(`/assessments/${summary.access_code}`)
    } catch (err) {
      if (err instanceof ApiError) {
        setError(err.message || "Couldn’t create the assessment.")
      } else {
        setError("Couldn’t reach the server. Try again shortly.")
      }
    } finally {
      setSaving(false)
    }
  }

  return (
    <div className="stack">
      <button type="button" className="text-link" onClick={() => navigate(-1)}>
        <ArrowLeft aria-hidden="true" /> Back to assessments
      </button>

      <PageHeader
        eyebrow="New assessment"
        title="Create an assessment"
        subtitle="Add a reading passage and 3–5 questions. Scheduling it gives every learner in the class a copy and a shared join code."
      />

      {/* AI drafting — turns the passage into skill-tagged questions */}
      <Card className="create__ai">
        <div className="create__ai-main">
          <span className="create__ai-icon">
            <Sparkles aria-hidden="true" />
          </span>
          <div>
            <h3 className="create__ai-title">
              Draft questions with AI
              <Badge tone="accent">Beta</Badge>
            </h3>
            <p className="create__ai-desc">
              Paste or scan a passage into the field below, then let AI draft a
              set of skill-tagged questions for you to review and edit. (Tip:
              use "Scan a page" on the Assessments screen to pull text from a
              photo first.)
            </p>
          </div>
        </div>
        <Button
          variant="outline"
          icon={Sparkles}
          onClick={draftFromPassage}
          disabled={drafting}
        >
          {drafting ? "Drafting…" : "Draft from passage"}
        </Button>
      </Card>

      {draftNote ? (
        <p className="create__draft-note" role="status">
          {draftNote}
        </p>
      ) : null}

      <Card>
        <Card.Header title="Details" />
        <Card.Body>
          <div className="stack">
            <Input
              label="Title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g. The Lighthouse Keeper"
            />
            <Input
              label="Category"
              value={category}
              onChange={(e) => setCategory(e.target.value)}
              placeholder="e.g. Fiction"
            />
            <Input
              label="Scheduled for"
              type="date"
              value={scheduledFor}
              onChange={(e) => setScheduledFor(e.target.value)}
            />
            <div className="field">
              <label className="field__label" htmlFor="passage">
                Passage
              </label>
              <textarea
                id="passage"
                className="create__passage"
                rows={9}
                value={passage}
                onChange={(e) => setPassage(e.target.value)}
                placeholder="Paste the reading passage students will see…"
              />
            </div>
          </div>
        </Card.Body>
      </Card>

      <Card>
        <Card.Header
          title="Questions"
          subtitle="3–5 questions. Tag each with the skill it targets and the key ideas a correct answer should mention."
        />
        <Card.Body>
          <div className="stack">
            {questions.map((q, i) => (
              <div className="create__q" key={i}>
                <div className="create__q-head">
                  <span className="create__q-num">Question {i + 1}</span>
                  <button
                    type="button"
                    className="create__q-remove"
                    onClick={() => removeQuestion(i)}
                    disabled={questions.length <= 3}
                    aria-label={`Remove question ${i + 1}`}
                  >
                    <Trash2 aria-hidden="true" />
                  </button>
                </div>
                <Input
                  label="Question"
                  value={q.question_text}
                  onChange={(e) =>
                    setQuestion(i, { question_text: e.target.value })
                  }
                  placeholder="e.g. What is the main idea of the passage?"
                />
                <Input
                  label="Expected ideas"
                  value={q.expected_ideas}
                  onChange={(e) =>
                    setQuestion(i, { expected_ideas: e.target.value })
                  }
                  placeholder="Key points a correct answer should mention"
                />
                <div className="field">
                  <label className="field__label" htmlFor={`skill-${i}`}>
                    Skill
                  </label>
                  <div className="field__control">
                    <select
                      id={`skill-${i}`}
                      className="create__select"
                      value={q.skill}
                      onChange={(e) => setQuestion(i, { skill: e.target.value })}
                    >
                      {SKILLS.map((s) => (
                        <option key={s.key} value={s.key}>
                          {s.label}
                        </option>
                      ))}
                    </select>
                  </div>
                </div>
              </div>
            ))}
            <Button
              variant="outline"
              icon={Plus}
              onClick={addQuestion}
              disabled={questions.length >= 5}
            >
              Add question
            </Button>
          </div>
        </Card.Body>
      </Card>

      {error ? (
        <p className="create__error" role="alert">
          {error}
        </p>
      ) : null}

      <div className="create__actions">
        <Button variant="ghost" onClick={() => navigate("/assessments")}>
          Cancel
        </Button>
        <Button icon={ClipboardList} onClick={onSave} disabled={saving}>
          {saving ? "Scheduling…" : "Create & get code"}
        </Button>
      </div>
    </div>
  )
}